### PR TITLE
Add TLS support

### PR DESCRIPTION
**Pull request by sporejack**
# Motivation
Despite orders being signed via EIP-712, it's still nice to know which web server you're talking to!

# Changes
 - Add CLI/env arguments for TLS certificate and associated private key
 - Modify web server call to listen on TLS

### CODE REVIEW

**Review by raymogg — CHANGES_REQUESTED** [review]
@sporejack does this mean that a cert is required to start the server, and it won't start without one?

**Comment by sporejack** [comment]
> @sporejack does this mean that a cert is required to start the server, and it won't start without one?

Yes, would you like a flag for HTTP?

**Comment by raymogg** [comment]
> > @sporejack does this mean that a cert is required to start the server, and it won't start without one?
> 
> Yes, would you like a flag for HTTP?

Yeah I reckon so. Just thinking in terms of local dev, this will stop us being able to spin it up quickly

**Comment by raymogg** [comment]
LGTM, only comment is we should document the flags (can probably be a separate PR)

**Pull request merged**
